# Generated by Django 4.2.7 on 2023-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoClassApp', '0002_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=10000)),
            ],
        ),
    ]
