# Generated by Django 4.2.7 on 2023-11-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoClassApp', '0004_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='detail',
            new_name='details',
        ),
    ]
