# Generated by Django 4.2.7 on 2023-11-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoClassApp', '0005_rename_detail_services_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
    ]
